---
name: Track releases (local)

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    name: Run release-please
    uses: ./.github/workflows/release.yml
    with:
      tag_major_minor_versions: true
    secrets:
      RELEASE_PLEASE_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
